### ISSUE TITLE
crear una aplicación móvil usando React Native

### ISSUE THREAD

**Issue by billygl** [gasparnd/lolocar#1]
Necesitamos una pantalla de bienvenida para nuestra aplicación móvil que estará hecha en react native. Esta es la pantalla a implementar:
![image](https://user-images.githubusercontent.com/442925/207969832-490958f1-4fc3-426c-ad90-e361f4c5fae3.png)

Y considera una caja de texto que cuando se ingresa un nombre mayor a 3 caracteres muestra el mensaje de Hola con el nombre ingresado como se muestra en la imagen.

Como es urgente, esperamos que sea resuelto en el menor tiempo posible pero con la mayor calidad posible.

**Comment by gasparnd** [comment]
Challenge ready!
